exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return Promise.all([
        knex.raw('ALTER SEQUENCE users_id_seq RESTART'),
        knex('users').insert({
          linkedin_id: 'wUg_HTKQrf',
          first_name: 'David',
          last_name: 'Ng',
          email_address: 'david@test.com',
          headline: 'Student at Lighthouse Labs',
          location: 'Vancouver, Canada',
          industry: 'Software engineering',
          current_share: 'Top 10 companies to work for in 2016',
          num_connections: 20,
          summary: 'Junior full stack web developer looking to incorporate background of finance and investments, economics, and mathematics to contribute to a team in the rapidly growing field of financial technology. I believe that intuitively designed UX that "just works" along with a beautifully crafted UI is of the utmost importance for any piece of software. I have a passion for self_improvement and I enjoy reading and studying the leaders and innovators of today.',
          positions: 0,
          picture_url: 'https://media.licdn.com/media/AAEAAQAAAAAAAAsjAAAAJDhmYzBmNDU0LTNlZTAtNGZmNi1iMmE4LTIzYzZjNTRiOWRlZQ.jpg',
          public_profile_url: 'https://www.linkedin.com/in/davidng6/',
          associations: JSON.stringify(['Lighthouse Labs', 'Computer club']),
          interests: JSON.stringify(['Coding', 'Hockey']),
          publications: JSON.stringify(['Eloquent SQL']),
          skills: JSON.stringify(['HTML', 'CSS', 'SQL']),
          certifications: JSON.stringify(['CSC']),
          educations: JSON.stringify(['Lighthouse Labs', 'University of Toronto']),
          courses: JSON.stringify(['CS50']),
          volunteer: JSON.stringify(['Heart2Heart']),
          three_past_positions: JSON.stringify(['Sales Associate', 'Web Developer']),
          following: JSON.stringify(['Bill Gates']),
          job_bookmarks: JSON.stringify(['Fintech', 'Software Engineering']),
          suggestions: JSON.stringify(['Richard Hsieh']),
          honors_awards: JSON.stringify([])
        }),
        knex('users').insert({
          linkedin_id: 'ir4W_5nelk',
          first_name: 'Hans',
          last_name: 'Kurniadi',
          email_address: 'hans@test.com',
          headline: 'Intern at Citi',
          location: 'Coquitlam, Canada',
          industry: 'Software engineering',
          current_share: 'How to be great at CSS',
          num_connections: 37,
          summary: 'Junior full stack web developer interested in financial technology industry',
          positions: 0,
          picture_url: '',
          public_profile_url: 'https://www.linkedin.com/in/hanskurniadi/',
          associations: JSON.stringify(['Lighthouse Labs', 'Citibank', 'fashion']),
          interests: JSON.stringify(['Coding', 'Eating', 'Fashion']),
          publications: JSON.stringify(['Eloquent Javascript']),
          skills: JSON.stringify(['Bootstrap', 'React', 'SQL']),
          certifications: JSON.stringify(['CFA']),
          educations: JSON.stringify(['Lighthouse Labs', 'Simon Fraser University']),
          courses: JSON.stringify(['Bootstrap']),
          volunteer: JSON.stringify(['WeCare']),
          three_past_positions: JSON.stringify([]),
          following: JSON.stringify(['Jeff Bezos']),
          job_bookmarks: JSON.stringify(['Fintech', 'Software Engineering', 'Web design']),
          suggestions: JSON.stringify(['Richard Hsieh', 'David Ng']),
          honors_awards: JSON.stringify(['Honour roll'])
        }),
        knex('users').insert({
          linkedin_id: 'BFPE3fSyXp',
          first_name: 'Richard',
          last_name: 'Hsieh',
          email_address: 'richard@test.com',
          headline: 'Assistant Sales Manager at Tropical Link Canada Ltd',
          location: 'Montreal, Canada',
          industry: 'Software engineering',
          current_share: '',
          num_connections: 50,
          summary: 'Junior full stack web developer with background in marketing.',
          positions: 0,
          picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAA0CAAAAJDg3YzIwODI0LWFlZjAtNDQwYy05YmYxLTUwYzU2N2YxOGFhMg.jpg',
          public_profile_url: 'https://www.linkedin.com/in/richard-hsieh-a2a43228/',
          associations: JSON.stringify(['Lighthouse Labs', 'Tropical Link Canada Ltd.', 'McGill University']),
          interests: JSON.stringify(['Coding', 'Eating', 'Networking']),
          publications: JSON.stringify(['Marketing 101']),
          skills: JSON.stringify(['Networking', 'Angular', 'MySQL']),
          certifications: JSON.stringify([]),
          educations: JSON.stringify(['Lighthouse Labs', 'McGill University']),
          courses: JSON.stringify(['HTML500']),
          volunteer: JSON.stringify(['WeCare']),
          three_past_positions: JSON.stringify([]),
          following: JSON.stringify(['Warren Buffett']),
          job_bookmarks: JSON.stringify(['Marketing', 'Software Engineering', 'Sales']),
          suggestions: JSON.stringify(['Kirat Virk']),
          honors_awards: JSON.stringify(['Honour roll'])
        }),
        knex('users').insert({
          linkedin_id: 'ITD8Ay4qmn',
          first_name: 'Kirat',
          last_name: 'Virk',
          email_address: 'kirat@test.com',
          headline: 'Full Stack Web Developer seeking opportunities',
          location: 'Vancouver, Canada',
          industry: 'Independent',
          current_share: '',
          num_connections: 28,
          summary: 'Junior full stack web developer with background in electrical engineering.',
          positions: 0,
          picture_url: '',
          public_profile_url: 'https://www.linkedin.com/in/kirat-virk-a2268a95/',
          associations: JSON.stringify(['Lighthouse Labs', 'University of British Columbia', 'Simon Fraser University']),
          interests: JSON.stringify(['Coding', 'Simpsons', 'Hardware']),
          publications: JSON.stringify(['Back end coding 101']),
          skills: JSON.stringify(['Knex', 'React', 'PostgreSQL']),
          certifications: JSON.stringify(['Certified engineer']),
          educations: JSON.stringify(['Lighthouse Labs', 'University of British Columbia', 'Simon Fraser University']),
          courses: JSON.stringify(['C#']),
          volunteer: JSON.stringify(['CodeDoesGood']),
          three_past_positions: JSON.stringify([]),
          following: JSON.stringify(['Elon Musk']),
          job_bookmarks: JSON.stringify(['Database', 'Software Engineering', 'Hardware']),
          suggestions: JSON.stringify(['David Ng', 'Hans Kurniadi', 'Richard Hsieh']),
          honors_awards: JSON.stringify(['First Honors Graduate'])
        }),
        knex('users').insert({
          linkedin_id: 'newa21ILdX',
          first_name: 'Anthony',
          last_name: 'Chan',
          email_address: 'anthony@test.com',
          headline: 'Fashion designer seeking opportunities',
          location: 'Calgary, Canada',
          industry: 'Fashion',
          current_share: '101 Fashion Faux Pas',
          num_connections: 214,
          summary: 'Fashion designer with lots of experience working with Zara, Gucci, creative director of H&M previously.',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: 'https://www.linkedin.com/in/anthony-chan-a0329bad/',
          associations: JSON.stringify(['Fashion', 'University of British Columbia', 'University of Alberta']),
          interests: JSON.stringify(['Fashion', 'Technology', 'Design']),
          publications: JSON.stringify(['Smart attire']),
          skills: JSON.stringify(['Creative', 'Fashion']),
          certifications: JSON.stringify(['Fashion']),
          educations: JSON.stringify(['Emily Carr University', 'Sir Winston Churchill Secondary']),
          courses: JSON.stringify(['Communications Design']),
          volunteer: JSON.stringify(['Fashion Does Good']),
          three_past_positions: JSON.stringify(['H&M', 'Zara', 'Gucci']),
          following: JSON.stringify(['Hedi Slimane']),
          job_bookmarks: JSON.stringify(['Fashion Designer', 'Creative Director', 'Sales']),
          suggestions: JSON.stringify(['David Ng']),
          honors_awards: JSON.stringify(['']),
          position_company_name: JSON.stringify(['Nike']),
          position_company_industry: JSON.stringify(['Sporting Goods']),
          position_company_type: JSON.stringify(['Public Company']),
          position_company_location: JSON.stringify(['Calgary, Canada']),
          position_company_summary: JSON.stringify(['Creative Director of Nike, in charge of all operations in design']),
          position_company_title: JSON.stringify(['Creative Director'])
        }),
        knex('users').insert({
          linkedin_id: 'nInvwow3Nk',
          first_name: 'Marco',
          last_name: 'Smith',
          email_address: 'marco@test.com',
          headline: 'Senior software engineer, previously Chief Technology Officer at Microsoft',
          location: 'Seattle, United States',
          industry: 'Software Engineer',
          current_share: 'Big Four Tech Companies',
          num_connections: 749,
          summary: 'Senior software engineer seeking new position, Chief Technology Officer at Microsoft previously.',
          positions: 0,
          picture_url: 'http://media.com',
          public_profile_url: 'https://www.linkedin.com/in/marco-smith-noa83nad/',
          associations: JSON.stringify(['Massachusetts Institute of Technology', 'Stanford University']),
          interests: JSON.stringify(['Machine Learning', 'Technology', 'Artificial Intelligence', 'IoT']),
          publications: JSON.stringify(['Artificial Intelligence']),
          skills: JSON.stringify(['Project Management', 'Back-end programming', 'Database Management']),
          certifications: JSON.stringify(['']),
          educations: JSON.stringify(['Massachusetts Institute of Technology', 'Stanford University']),
          courses: JSON.stringify(['Artificial Intelligence', 'Machine Learning']),
          volunteer: JSON.stringify(['Bill & Melinda Gates Foundation']),
          three_past_positions: JSON.stringify(['Uber', 'Amazon', 'Morgan Stanley']),
          following: JSON.stringify(['Warren Buffett', 'Richard Branson']),
          job_bookmarks: JSON.stringify(['Software Engineer', 'Technology Officer', 'Leader']),
          suggestions: JSON.stringify(['Kirat Virk']),
          honors_awards: JSON.stringify(['Artificial Intelligence']),
          position_company_name: JSON.stringify([]),
          position_company_industry: JSON.stringify([]),
          position_company_type: JSON.stringify([]),
          position_company_location: JSON.stringify([]),
          position_company_summary: JSON.stringify([]),
          position_company_title: JSON.stringify([])
        }),
        knex('users').insert({
          linkedin_id: 'MnvioAS390',
          first_name: 'Bill',
          last_name: 'Gates',
          email_address: 'billgates@test.com',
          headline: 'Co-chair, Bill & Melinda Gates Foundation',
          location: 'Greater Seattle Area',
          industry: 'Philanthropy',
          current_share: 'Warren Buffet\'s Best Investment',
          num_connections: 74912,
          summary: 'Co-chair of the Bill & Melinda Gates Foundation. Microsoft Co-founder. Voracious reader. Avid traveler. Active blogger.',
          positions: 2,
          picture_url: 'http://billgates.com',
          public_profile_url: 'https://www.linkedin.com/in/williamhgates/',
          associations: JSON.stringify(['UNAIDS', 'Bill & Melinda Gates Foundation', 'Water.org', 'USAID', 'LinkedIn']),
          interests: JSON.stringify(['Machine Learning', 'Artificial Intelligence', 'Philanthropy', 'Social']),
          publications: JSON.stringify(['Importance of Philanthropy']),
          skills: JSON.stringify(['Vision', 'Programming']),
          certifications: JSON.stringify(['Nobel Prize']),
          educations: JSON.stringify(['Harvard University', 'Lakeside School, Seattle']),
          courses: JSON.stringify(['Artificial Intelligence', 'Machine Learning']),
          volunteer: JSON.stringify(['Bill & Melinda Gates Foundation']),
          three_past_positions: JSON.stringify(['Bill & Melinda Gates Foundation', 'Microsoft']),
          following: JSON.stringify(['UNAIDS', 'Bill & Melinda Gates Foundation', 'Water.org', 'USAID', 'LinkedIn', 'Reid Hoffman', 'Satya Nadella', 'Sue Desmond-Hellmann', 'Microsoft', 'Harvard University']),
          job_bookmarks: JSON.stringify([]),
          suggestions: JSON.stringify(['Kirat Virk', 'Marco Smith', 'Anthony Chan']),
          honors_awards: JSON.stringify(['Philanthropy']),
          position_company_name: JSON.stringify(['Bill & Melinda Gates Foundation', 'Microsoft']),
          position_company_industry: JSON.stringify(['Philanthropy', 'Technology']),
          position_company_type: JSON.stringify(['Philanthropy', 'Public Company']),
          position_company_location: JSON.stringify(['Seattle, United States', 'Seattle, United States']),
          position_company_summary: JSON.stringify(['Grant-making foundation supports initiatives in education, world health and population, and community giving in the Pacific Northwest.', 'At Microsoft our mission and values are to help people and businesses throughout the world realize their full potential.']),
          position_company_title: JSON.stringify(['Co-chair', 'Chairman'])
        }),
        knex('users').insert({
          linkedin_id: 'ITD2Av4qmn',
          first_name: 'Paul',
          last_name: 'Allen',
          email_address: 'paul@microsoft.com',
          headline: 'Founder of Microsoft',
          location: 'Seattle, Washington',
          industry: 'Computer Software',
          current_share: 'How to be successful',
          num_connections: 500,
          summary: 'Founder of a very successful software company and founder of the Bill Gates foundation helping get rid of malaria',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: 'https://www.linkedin.com/in/bill-gates-a2268a95/',
          associations: JSON.stringify(['Bill Gates Foundation', 'Microsoft']),
          interests: JSON.stringify(['Coding', 'Stopping Malaria', 'Hardware']),
          publications: JSON.stringify(['Stopping Malaria']),
          skills: JSON.stringify(['Programming', 'C', 'Marketing']),
          certifications: JSON.stringify(['']),
          educations: JSON.stringify(['Harvard']),
          courses: JSON.stringify(['ß']),
          volunteer: JSON.stringify(['Bill Gates Foundation']),
          three_past_positions: JSON.stringify(['BIll Gates Foundation', 'Microsoft']),
          following: JSON.stringify(['Elon Musk', 'Steve Balmer']),
          job_bookmarks: JSON.stringify(['Database', 'Software Engineering', 'Hardware']),
          suggestions: JSON.stringify(['Steve Balmer', 'Paul Allen', 'Steve Wozniak']),
          honors_awards: JSON.stringify(['First Honors Graduate']),
          position_company_name: JSON.stringify(['Bill Gates Foundation', 'string2']),
          position_company_industry: JSON.stringify(['Charity', 'string2']),
          position_company_type: JSON.stringify(['string1', 'string2']),
          position_company_location: JSON.stringify(['string1', 'string2']),
          position_company_summary: JSON.stringify(['Helping Stop Malaria']),
          position_company_title: JSON.stringify(['Founder'])
        }),
        knex('users').insert({
          linkedin_id: 'ITD8Ay42sn',
          first_name: 'Dean',
          last_name: 'Anderson',
          email_address: 'dean@gmail.com',
          headline: 'Co-Founder at Mysseur / Web Developer',
          location: 'Vancouver, Canada',
          industry: 'Computer Software',
          current_share: 'How to be successful',
          num_connections: 500,
          summary: 'Specialties: Web Development, Web Design, Drupal, Yii Framework, PHP, MySQL, HTML5, CSS3, JavaScript, jQuery, User Interface Design, User Experience Design',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: "https://www.linkedin.com/in/Dean-Anderson-a2268a95/",
          associations: JSON.stringify(['UBC']),
          interests: JSON.stringify(['']),
          publications: JSON.stringify(['Web Development', 'User Interface Design', 'Web Design', 'PHP', 'HTML5', 'CSS3', 'JavaScriptAngularJSUser', 'Experience', 'Design', 'Problem Solving', 'Backend Development', 'Front-end Development', 'jQuery', 'Drupal', 'MySQL', 'CSS', 'Web Applications', 'Linux', 'HTML5']),
          skills: JSON.stringify(['Programming', 'React', 'PostgreSQL']),
          certifications: JSON.stringify(['']),
          educations: JSON.stringify(['University of British Columbia', 'University of Saskatchewan']),
          courses: JSON.stringify(['']),
          volunteer: JSON.stringify(['']),
          three_past_positions: JSON.stringify(['Freelance Web Developer \/ UI Designer', 'Freelance Web Developer \/ UI Designer']),
          following: JSON.stringify(['Bill Gates']),
          job_bookmarks: JSON.stringify(['Database', 'Software Engineering', 'Hardware']),
          suggestions: JSON.stringify(['David Ng', 'Hans Kurniadi']),
          honors_awards: JSON.stringify(['First Honors Graduate']),
          position_company_name: JSON.stringify(['mysseur', 'string2']),
          position_company_industry: JSON.stringify(['Web Development', 'string2']),
          position_company_type: JSON.stringify(['string1', 'string2']),
          position_company_location: JSON.stringify(['string1', 'string2']),
          position_company_summary: JSON.stringify(['Full-stack development of a custom web and mobile reservation / booking platform. Technologies include a PHP backend, custom API, JavaScript + AngularJS, CSS3 and HTML5.']),
          position_company_title: JSON.stringify(['Co-Founder / Developer'])
        }),
        knex('users').insert({
          linkedin_id: 'FBD8Ay42sn',
          first_name: 'John',
          last_name: 'Smith',
          email_address: 'john@smith.com',
          headline: 'Cashier at McDonalds',
          location: 'Vancouver, Canada',
          industry: 'Restaurant',
          current_share: 'How to be successful',
          num_connections: 10,
          summary: 'I am a cashier at McDonalds',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: "https://www.linkedin.com/in/John-Smith-a2268a95/",
          associations: JSON.stringify(['']),
          interests: JSON.stringify(['Surfing','Skateboarding']),
          publications: JSON.stringify(['']),
          skills: JSON.stringify([]),
          certifications: JSON.stringify(['']),
          educations: JSON.stringify(['High School for the Arts']),
          courses: JSON.stringify(['']),
          volunteer: JSON.stringify(['']),
          three_past_positions: JSON.stringify(['']),
          following: JSON.stringify(['Bill Gates']),
          job_bookmarks: JSON.stringify(['']),
          suggestions: JSON.stringify(['Bart Smith', 'Eric Watts']),
          honors_awards: JSON.stringify(['First Honors Graduate']),
          position_company_name: JSON.stringify(['McDonalds', 'string2']),
          position_company_industry: JSON.stringify(['Restaurant', 'string2']),
          position_company_type: JSON.stringify(['string1', 'string2']),
          position_company_location: JSON.stringify(['string1', 'string2']),
          position_company_summary: JSON.stringify(['']),
          position_company_title: JSON.stringify(['Cashier'])
        }),
        knex('users').insert({
          linkedin_id: 'ITDqa21qmn',
          first_name: 'Robert',
          last_name: 'Johnson',
          email_address: 'robertj@hotmail.com',
          headline: 'Civil Engineering Gradute. Freelance Designer',
          location: 'Burnaby, Canada',
          industry: 'Independent',
          current_share: 'How to draw',
          num_connections: 54,
          summary: 'As a freelance graphic and web designer, I combine an eye for detail with a acute understanding of colors and shapes to develop effective branding solutions for various needs.',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Robert_Johnson.png',
          associations: JSON.stringify(['McGill University', 'CEGEP Champlain St. Lambert', 'College de Montreal']),
          interests: JSON.stringify(['Drawing']),
          publications: JSON.stringify(['']),
          skills: JSON.stringify(['Adobe Creative', 'Microsoft Office', 'AutoCAD']),
          certifications: JSON.stringify(['Certified engineer']),
          educations: JSON.stringify(['McGill University', 'CEGEP Champlain St. Lambert', 'College de Montreal']),
          courses: JSON.stringify(['']),
          volunteer: JSON.stringify(['The Association of the Friends of Jimma']),
          three_past_positions: JSON.stringify(['Self-Employed', 'VP Finance', 'Structural Engineer Summer Intern']),
          following: JSON.stringify(['McGill Black Alumni Association', 'McGill University', 'Arup', 'Pulse', 'McGIll Faculty of Engineering', 'TVM Student TV at McGill']),
          job_bookmarks: JSON.stringify(['']),
          suggestions: JSON.stringify(['Bob doe', 'Hans Kurniadi', 'Kirat Virk']),
          honors_awards: JSON.stringify(['']),
          position_company_name: JSON.stringify(['Self-Employed']),
          position_company_industry: JSON.stringify(['']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Montreal, Quebec, Canada']),
          position_company_summary: JSON.stringify(['As a freelance graphic and web designer, I combine an eye for detail with a acute understanding of colors and shapes to develop effective branding solutions for various needs.']),
          position_company_title: JSON.stringify([''])
        }),
        knex('users').insert({
          linkedin_id: 'I234Ay4qmn',
          first_name: 'Nazir',
          last_name: 'Ali',
          email_address: 'nazirali@gmail.com',
          headline: 'Frontend Lead at the Coding Bull',
          location: 'Vancouver, British Columbia, Canada',
          industry: 'Independent',
          current_share: '',
          num_connections: 401,
          summary: 'No need to beat around the bush. Here comes my humble brag. I am a self-taught frontend/ UI engineer with an engineering degree from McGill and a passion for unique web presentation and experience. I am also a freelance graphic artist and a sketch artist. I went into web development after the completion of my chemical engineering degree from McGill University. I made the transition into tech to explore my potential in a fast paced industry, where I could put my technical and creative excellence to good use, and to one day create oatmeal.js. Currently, I am a frontend lead at a Vancouver based web agency called The Coding Bull. My work at a startup has allowed me to explore and drastically develop my skills in different areas of web development within a very short amount of time. Highly skilled in UI dev, I write clean CSS at a pace you\'ve probably never seen before, and is solely in charge of crafting responsive, beautiful designs of all our products. Moving backwards, I am proficient in javascript with solid knowledge of react.js. I also maintain a high level of reusability and scalability in my code. I am currently learning ruby on rails, and assist backend devs in backend architecture of our apps. I have experience working with several APIs including rails, google maps, stripe, and parse, firebase and postgres. I also have experience working on a mobile platform using react native and occasional java and objective-c. I was initially hired as a graphic designer by The Coding Bull. On average, I spend 4 days working dev-mode, and turn on the right side of my brain for a full day to design logos, coffee mugs, wireframes or whatever is on the table. Thank god I\'m not doing instagram posting anymore. I believe myself to be highly adaptable and a very fast learner. The only way to know is to do, and I want to know a lot. Thank you..',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: 'https://travsd.files.wordpress.com/2013/09/young_bill_murray.jpg',
          associations: JSON.stringify(['University of Toronto', 'The International School Bangalore']),
          interests: JSON.stringify(['Dancing']),
          publications: JSON.stringify(['']),
          skills: JSON.stringify(['HTML5', 'CSS', 'Javascript','Angular','Photoshop', 'Chemical Engineering', 'C', 'Node.js','Microsoft Office','Backbone.js','Logo Design','React.js', 'React.js','Illustrator', 'jQuery','Engineering','Mathlab','Teamwork', 'Python']),
          certifications: JSON.stringify(['Certified engineer']),
          educations: JSON.stringify(['University of British Columbia', 'The International School Bangalore']),
          courses: JSON.stringify(['ADvanced Calculus for Engineers', 'Advanced Separation Processes','Chemical Manufacturing Processes','Chemical Reactions Engineering']),
          volunteer: JSON.stringify(['']),
          three_past_positions: JSON.stringify(['Frontend Developer', 'Front-end Consultant','Freelance Web Developer and Designer']),
          following: JSON.stringify(['QuickMobile','Green Business','Shomi','Flatbook','Design']),
          job_bookmarks: JSON.stringify(['Front-end']),
          suggestions: JSON.stringify(['Bob doe', 'Jane White' , 'James Johnson']),
          honors_awards: JSON.stringify(['Recipient of the National Science and Engineering Research Council of Canada Research scholarship']),
          position_company_name: JSON.stringify(['littlefleets']),
          position_company_industry: JSON.stringify(['Technology']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Vancouver, British Columbia, Canada']),
          position_company_summary: JSON.stringify(['']),
          position_company_title: JSON.stringify(['Frontend Lead'])
        }),
        knex('users').insert({
          linkedin_id: 'I234Ay343a',
          first_name: 'Steve',
          last_name: 'Wozniak',
          email_address: 's.wozniak@sandisk.com',
          headline: 'Fellow at Apple',
          location: 'San Francisco, Bay Arearr',
          industry: 'Computer Software',
          current_share: '',
          num_connections: 500,
          summary: '',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: 'http://pmc.com/wp-content/uploads/2014/07/03_PMC_Board_Bio_Wozniak-289x407.png',
          associations: JSON.stringify(['University of California, Berkeley', 'University of Colorado Boulder']),
          interests: JSON.stringify(['Coding']),
          publications: JSON.stringify(['']),
          skills: JSON.stringify(['']),
          certifications: JSON.stringify(['']),
          educations: JSON.stringify(['University of California, Berkeley', 'University of Colorado Boulder']),
          courses: JSON.stringify(['']),
          volunteer: JSON.stringify(['']),
          three_past_positions: JSON.stringify(['Chief Scientist', 'Fellow','President & CTO']),
          following: JSON.stringify(['Wheels of Zeus',' University of California, Berkeley','Pulse','NEW Homebrew Computer Club','Walter Isaacson']),
          job_bookmarks: JSON.stringify(['']),
          suggestions: JSON.stringify(['Bill Gates', 'Paul Allen']),
          honors_awards: JSON.stringify(['']),
          position_company_name: JSON.stringify(['Fusion-io']),
          position_company_industry: JSON.stringify(['Software']),
          position_company_type: JSON.stringify(['Technology']),
          position_company_location: JSON.stringify(['']),
          position_company_summary: JSON.stringify(['I\'m looking into future technologies applicable to servers and storage, and helping this company, which I love, get noticed and get a lead so that the world can discover the new amazing technology they have developed. My role is principally a marketing one at present but that will change over time.']),
          position_company_title: JSON.stringify(['Chief Scientist'])
        })
      ]);
    });
};
