exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return Promise.all([
        knex.raw('ALTER SEQUENCE users_id_seq RESTART'),
        knex('users').insert({
          linkedin_id: 'BFPE3fSyXp',
          first_name: 'Richard',
          last_name: 'Hsieh',
          email_address: 'richard@test.com',
          headline: 'Assistant Sales Manager at Tropical Link Canada Ltd',
          location: 'Montreal, Canada',
          industry: 'Software engineering',
          current_share: '',
          num_connections: 50,
          summary: 'Junior full stack web developer with background in marketing.',
          positions: 0,
          picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAA0CAAAAJDg3YzIwODI0LWFlZjAtNDQwYy05YmYxLTUwYzU2N2YxOGFhMg.jpg',
          public_profile_url: 'https://www.linkedin.com/in/richard-hsieh-a2a43228/',
          position_company_name: JSON.stringify([]),
          position_company_industry: JSON.stringify([]),
          position_company_type: JSON.stringify([]),
          position_company_location: JSON.stringify([]),
          position_company_summary: JSON.stringify([]),
          position_company_title: JSON.stringify([])
        }),
        knex('users').insert({
          linkedin_id: 'ITD8Ay4qmn',
          first_name: 'Kirat',
          last_name: 'Virk',
          email_address: 'kirat@test.com',
          headline: 'Full Stack Web Developer seeking opportunities',
          location: 'Vancouver, Canada',
          industry: 'Independent',
          current_share: '',
          num_connections: 28,
          summary: 'Junior full stack web developer with background in electrical engineering.',
          positions: 0,
          public_profile_url: 'https://www.linkedin.com/in/kirat-virk-a2268a95/',
          position_company_name: JSON.stringify([]),
          position_company_industry: JSON.stringify([]),
          position_company_type: JSON.stringify([]),
          position_company_location: JSON.stringify([]),
          position_company_summary: JSON.stringify([]),
          position_company_title: JSON.stringify([])
        }),
        knex('users').insert({
          linkedin_id: 'newa21ILdX',
          first_name: 'Anthony',
          last_name: 'Chan',
          email_address: 'anthony@test.com',
          headline: 'Fashion designer seeking opportunities',
          location: 'Calgary, Canada',
          industry: 'Fashion',
          current_share: '101 Fashion Faux Pas',
          num_connections: 214,
          summary: 'Fashion designer with lots of experience working with Zara, Gucci, creative director of H&M previously.',
          positions: 1,
          public_profile_url: 'https://www.linkedin.com/in/anthony-chan-a0329bad/',
          position_company_name: JSON.stringify(['Nike']),
          position_company_industry: JSON.stringify(['Sporting Goods']),
          position_company_type: JSON.stringify(['Public Company']),
          position_company_location: JSON.stringify(['Calgary, Canada']),
          position_company_summary: JSON.stringify(['Creative Director of Nike, in charge of all operations in design']),
          position_company_title: JSON.stringify(['Creative Director'])
        }),
        knex('users').insert({
          linkedin_id: 'nInvwow3Nk',
          first_name: 'Marco',
          last_name: 'Smith',
          email_address: 'marco@test.com',
          headline: 'Senior software engineer, previously Chief Technology Officer at Microsoft',
          location: 'Seattle, United States',
          industry: 'Software Engineer',
          current_share: 'Big Four Tech Companies',
          num_connections: 749,
          summary: 'Senior software engineer seeking new position, Chief Technology Officer at Microsoft previously.',
          positions: 0,
          public_profile_url: 'https://www.linkedin.com/in/marco-smith-noa83nad/',
          position_company_name: JSON.stringify([]),
          position_company_industry: JSON.stringify([]),
          position_company_type: JSON.stringify([]),
          position_company_location: JSON.stringify([]),
          position_company_summary: JSON.stringify([]),
          position_company_title: JSON.stringify([])
        }),
        knex('users').insert({
          linkedin_id: 'MnvioAS390',
          first_name: 'Bill',
          last_name: 'Gates',
          email_address: 'billgates@test.com',
          headline: 'Co-chair, Bill & Melinda Gates Foundation',
          location: 'Greater Seattle Area',
          industry: 'Philanthropy',
          current_share: 'Warren Buffet\'s Best Investment',
          num_connections: 74912,
          summary: 'Co-chair of the Bill & Melinda Gates Foundation. Microsoft Co-founder. Voracious reader. Avid traveler. Active blogger.',
          positions: 2,
          public_profile_url: 'https://www.linkedin.com/in/williamhgates/',
          position_company_name: JSON.stringify(['Bill & Melinda Gates Foundation', 'Microsoft']),
          position_company_industry: JSON.stringify(['Philanthropy', 'Technology']),
          position_company_type: JSON.stringify(['Philanthropy', 'Public Company']),
          position_company_location: JSON.stringify(['Seattle, United States', 'Seattle, United States']),
          position_company_summary: JSON.stringify(['Grant-making foundation supports initiatives in education, world health and population, and community giving in the Pacific Northwest.', 'At Microsoft our mission and values are to help people and businesses throughout the world realize their full potential.']),
          position_company_title: JSON.stringify(['Co-chair', 'Chairman'])
        }),
        knex('users').insert({
          linkedin_id: 'ITD2Av4qmn',
          first_name: 'Paul',
          last_name: 'Allen',
          email_address: 'paul@microsoft.com',
          headline: 'Founder of Microsoft',
          location: 'Seattle, Washington',
          industry: 'Computer Software',
          current_share: 'How to be successful',
          num_connections: 500,
          summary: 'Founder of a very successful software company and founder of the Bill Gates foundation helping get rid of malaria',
          positions: 1,
          public_profile_url: 'https://www.linkedin.com/in/bill-gates-a2268a95/',
          position_company_name: JSON.stringify(['Bill Gates Foundation', 'string2']),
          position_company_industry: JSON.stringify(['Charity', 'string2']),
          position_company_type: JSON.stringify(['string1', 'string2']),
          position_company_location: JSON.stringify(['string1', 'string2']),
          position_company_summary: JSON.stringify(['Helping Stop Malaria']),
          position_company_title: JSON.stringify(['Founder'])
        }),
        knex('users').insert({
          linkedin_id: 'ITD8Ay42sn',
          first_name: 'Dean',
          last_name: 'Anderson',
          email_address: 'dean@gmail.com',
          headline: 'Co-Founder at Mysseur / Web Developer',
          location: 'Vancouver, Canada',
          industry: 'Computer Software',
          current_share: 'How to be successful',
          num_connections: 500,
          summary: 'Specialties: Web Development, Web Design, Drupal, Yii Framework, PHP, MySQL, HTML5, CSS3, JavaScript, jQuery, User Interface Design, User Experience Design',
          positions: 1,
          public_profile_url: "https://www.linkedin.com/in/Dean-Anderson-a2268a95/",
          position_company_name: JSON.stringify(['mysseur', 'string2']),
          position_company_industry: JSON.stringify(['Web Development', 'string2']),
          position_company_type: JSON.stringify(['string1', 'string2']),
          position_company_location: JSON.stringify(['string1', 'string2']),
          position_company_summary: JSON.stringify(['Full-stack development of a custom web and mobile reservation / booking platform. Technologies include a PHP backend, custom API, JavaScript + AngularJS, CSS3 and HTML5.']),
          position_company_title: JSON.stringify(['Co-Founder / Developer'])
        }),
        knex('users').insert({
          linkedin_id: 'FBD8Ay42sn',
          first_name: 'John',
          last_name: 'Smith',
          email_address: 'john@smith.com',
          headline: 'Cashier at McDonalds',
          location: 'Vancouver, Canada',
          industry: 'Restaurant',
          current_share: 'How to be successful',
          num_connections: 10,
          summary: 'I am a cashier at McDonalds',
          positions: 1,
          picture_url: 'http://gif.com',
          public_profile_url: "https://www.linkedin.com/in/John-Smith-a2268a95/",
          position_company_name: JSON.stringify(['McDonalds', 'string2']),
          position_company_industry: JSON.stringify(['Restaurant', 'string2']),
          position_company_type: JSON.stringify(['string1', 'string2']),
          position_company_location: JSON.stringify(['string1', 'string2']),
          position_company_summary: JSON.stringify(['']),
          position_company_title: JSON.stringify(['Cashier'])
        }),
        knex('users').insert({
          linkedin_id: 'ITDqa21qmn',
          first_name: 'Robert',
          last_name: 'Johnson',
          email_address: 'robertj@hotmail.com',
          headline: 'Civil Engineering Gradute. Freelance Designer',
          location: 'Burnaby, Canada',
          industry: 'Independent',
          current_share: 'How to draw',
          num_connections: 54,
          summary: 'As a freelance graphic and web designer, I combine an eye for detail with a acute understanding of colors and shapes to develop effective branding solutions for various needs.',
          positions: 1,
          picture_url: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Robert_Johnson.png',
          public_profile_url: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Robert_Johnson.png',
          position_company_name: JSON.stringify(['Self-Employed']),
          position_company_industry: JSON.stringify(['']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Montreal, Quebec, Canada']),
          position_company_summary: JSON.stringify(['As a freelance graphic and web designer, I combine an eye for detail with a acute understanding of colors and shapes to develop effective branding solutions for various needs.']),
          position_company_title: JSON.stringify([''])
        }),
        knex('users').insert({
          linkedin_id: 'I234Ay4qmn',
          first_name: 'Nazir',
          last_name: 'Ali',
          email_address: 'nazirali@gmail.com',
          headline: 'Frontend Lead at the Coding Bull',
          location: 'Vancouver, British Columbia, Canada',
          industry: 'Independent',
          current_share: '',
          num_connections: 401,
          summary: 'No need to beat around the bush. Here comes my humble brag. I am a self-taught frontend/ UI engineer with an engineering degree from McGill and a passion for unique web presentation and experience. I am also a freelance graphic artist and a sketch artist. I went into web development after the completion of my chemical engineering degree from McGill University. I made the transition into tech to explore my potential in a fast paced industry, where I could put my technical and creative excellence to good use, and to one day create oatmeal.js. Currently, I am a frontend lead at a Vancouver based web agency called The Coding Bull. My work at a startup has allowed me to explore and drastically develop my skills in different areas of web development within a very short amount of time. Highly skilled in UI dev, I write clean CSS at a pace you\'ve probably never seen before, and is solely in charge of crafting responsive, beautiful designs of all our products. Moving backwards, I am proficient in javascript with solid knowledge of react.js. I also maintain a high level of reusability and scalability in my code. I am currently learning ruby on rails, and assist backend devs in backend architecture of our apps. I have experience working with several APIs including rails, google maps, stripe, and parse, firebase and postgres. I also have experience working on a mobile platform using react native and occasional java and objective-c. I was initially hired as a graphic designer by The Coding Bull. On average, I spend 4 days working dev-mode, and turn on the right side of my brain for a full day to design logos, coffee mugs, wireframes or whatever is on the table. Thank god I\'m not doing instagram posting anymore. I believe myself to be highly adaptable and a very fast learner. The only way to know is to do, and I want to know a lot. Thank you..',
          positions: 1,
          picture_url: 'https://travsd.files.wordpress.com/2013/09/young_bill_murray.jpg',
          public_profile_url: 'https://travsd.files.wordpress.com/2013/09/young_bill_murray.jpg',
          associations: JSON.stringify(['University of Toronto', 'The International School Bangalore']),
          position_company_name: JSON.stringify(['littlefleets']),
          position_company_industry: JSON.stringify(['Technology']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Vancouver, British Columbia, Canada']),
          position_company_summary: JSON.stringify(['']),
          position_company_title: JSON.stringify(['Frontend Lead'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC4BSy4qmn',
          first_name: 'Kobe',
          last_name: 'Eban',
          email_address: 'Kobeeban@gmail.com',
          headline: 'Amazon Vancouver is looking for talented Software Developers',
          location: 'Vancouver, British Columbia, Canada',
          industry: 'Software',
          current_share: '',
          num_connections: 500,
          summary: "For a list of open positions on my team refer to the following web page: http://bit.ly/2dpIEaC I'm an experienced professional who combines great communication and people skills with a keen intellect and understand of both business and technology. I am able to work with stakeholders to understand their problems and lead my team to solve them. I have traveled the world working on large complex projects and found people and process are often the most challenging aspect of any problem. At the same time working with people from different places, with different backgrounds and with different perspectives has also been and is still one of the most enjoyable aspects of my career. I have been working within the IT industry for than 12 years. For the last 5 years I have been working on managing large projects and teams. In this time I have had the opportunity to work with and understand two of the most important industries within modern business in Finance and Logistics. In addition to my management experience I have had extensive experience working as a Software Architect. This gives me good insight and understanding of system design that I leverage when leading initiatives for my organization. During my time as a Software Architect I was the lead architect on an initiative to redesign the way HSBC's Personal Banking systems were built. This was done in such a way that we could bring a modern architecture to HSBC while at the same time coexisting with legacy systems allowing the phased rollout and adoption of the new system. Specialties: Leadership, Problem Solving, Stakeholder Management, Product Management, Programme Management, Agile Project Management, Software Architecture, Communication, Team Building",
          positions: 6,
          picture_url: 'https://static1.squarespace.com/static/54b5404ce4b05d045de87038/5537f593e4b0a334dca05223/5644ed91e4b06918602c1d3a/1447357842725/Joe+Koufman+cartoon+headshot+-+2015.jpg',
          public_profile_url: 'https://static1.squarespace.com/static/54b5404ce4b05d045de87038/5537f593e4b0a334dca05223/5644ed91e4b06918602c1d3a/1447357842725/Joe+Koufman+cartoon+headshot+-+2015.jpg',
          position_company_name: JSON.stringify(['Amazon']),
          position_company_industry: JSON.stringify(['Technology']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Vancouver, British Columbia, Canada']),
          position_company_summary: JSON.stringify(['']),
          position_company_title: JSON.stringify(['Software Development Manager'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FCDAy4qmn',
          first_name: 'Alex',
          last_name: 'Ho',
          email_address: 'alexho@gmail.com',
          headline: 'Research Associate at Millipore Sigma',
          location: 'Allston, Massachusetts, USA',
          industry: 'Chemistry Engineering',
          current_share: '',
          num_connections: 18,
          summary: "I hold a degree in Chemical Engineering and am currently working at MilliporeSigma in the Single-Use Bioprocessing Product Development group. At Millipore I have had the chance to work on the development and validation of multiple different products, and I have thrived in a fast-paced and technically demanding R&D environment. I am a highly motivated and scientifically curious individual who is interested in challenging opportunities for career growth in product development.",
          positions: 1,
          picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAjoAAAAJDUxZWRmNmYzLTJmODItNDlmNy04MDA4LWRiOTI1NmZkODU0NQ.jpg',
          public_profile_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAjoAAAAJDUxZWRmNmYzLTJmODItNDlmNy04MDA4LWRiOTI1NmZkODU0NQ.jpg',
          position_company_name: JSON.stringify(['MilliporeSigma']),
          position_company_industry: JSON.stringify(['Chemistry Engineering']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Allston, Massachusetts, USA']),
          position_company_summary: JSON.stringify(["-Led a team investigating the use of vacuum-forming as a means of manufacturing plastic components for single-use bioprocessing applications. Oversaw the installation of a new vacuum former and designed custom tooling using SolidWorks. -Helped develop an automated integrity test instrument for membrane filtration devices. Gained technical expertise in filter integrity testing, collaborated with senior R&D engineers on the design and testing of hardware and software. Responsible for laboratory activities and validation testing. -Responsible for operation and preventative maintenance of a variety of laboratory equipment including DAQ test stands, vacuum forming equipment and analytical instruments. "]),
          position_company_title: JSON.stringify(['Research Associate'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC4ABAmn',
          first_name: 'Susan',
          last_name: 'Chan',
          email_address: 'susanchan@gmail.com',
          headline: 'Research Intern at Tropical Ltd',
          location: 'Vancouver, British Columbia, Canada',
          industry: 'Business',
          current_share: '',
          num_connections: 141,
          summary: "Currently a third year student studying Cognitive Systems and a minor in Economics at the University of British Columbia. Interested in the integration of technology, cognition, psychology, and business logistics. ",
          positions: 6,
          picture_url: 'https://s-media-cache-ak0.pinimg.com/originals/aa/e7/9c/aae79ce32a75827b35591a947f200d70.jpg',
          public_profile_url: 'https://s-media-cache-ak0.pinimg.com/originals/aa/e7/9c/aae79ce32a75827b35591a947f200d70.jpg',
          position_company_name: JSON.stringify(['entrepreneurship@UBC']),
          position_company_industry: JSON.stringify(['Business']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Vancouver, British Columbia, Canada']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['VP Logistics'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC4FAqmn',
          first_name: 'Emily',
          last_name: 'White',
          email_address: 'emilywhite@gmail.com',
          headline: 'Business Development Manager at Kubera Payments',
          location: 'Vancouver, British Columbia, Canada',
          industry: 'Business',
          current_share: '4',
          num_connections: 405,
          summary: "",
          positions: 5,
          picture_url: 'hhttps://s-media-cache-ak0.pinimg.com/originals/20/44/c8/2044c8c89a60a37a1ae247c17d935c4e.jpg',
          public_profile_url: 'https://s-media-cache-ak0.pinimg.com/originals/20/44/c8/2044c8c89a60a37a1ae247c17d935c4e.jpg',
          position_company_name: JSON.stringify(['Kubera Payments']),
          position_company_industry: JSON.stringify(['Technology']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Vancouver, British Columbia, Canada']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['Business Administration Coordinator'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC4A3121mn',
          first_name: 'Jane',
          last_name: 'Jin',
          email_address: 'janejin@gmail.com',
          headline: "CEO & Co-founder of room2learn // MDes Candidate at Harvard Graduate School of Design",
          location: 'Greater Boston Area',
          industry: 'Business',
          current_share: '4',
          num_connections: 405,
          summary: "Hello! I'm a spatial designer and entrepreneur working to reshape learning experiences in K-12 schools. Our team of educators, designers, and engineers is based out of the Harvard Innovation Lab. I am always open to connect with fellow innovators and educators looking to redesign their spaces.",
          positions: 7,
          picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/7/005/076/3d2/09c9e8f.jpg',
          public_profile_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/7/005/076/3d2/09c9e8f.jpg',
          position_company_name: JSON.stringify(['Room2Learn']),
          position_company_industry: JSON.stringify(['Business']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Greater Boston Area']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['CEO & Co-founder'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC4A23a4mn',
          first_name: 'Jerry',
          last_name: 'Wei',
          email_address: 'jerrywei@gmail.com',
          headline: "SDE Intern at Amazon Web Services",
          location: 'San Francisco Bay Area',
          industry: 'Technology',
          current_share: '',
          num_connections: 500,
          summary: "I am a Senior in Computer Science at McGill University, minoring in GIS and Field Studies. I am currently enrolled in a field semester in Barbados researching mapping in marine biology. Last winter I studied in Belgium, at the Université Catholique de Louvain. My experience living and working in three different continents makes me a global candidate, willing to adapt and integrate into any team. I interned at Ericsson last year for 8 months as a Services Engineer - the job description included monitoring and field testing for Key Performance Indicators (KPIs) and consulting with clients (internal & external) over conference calls each day. I also have extensive research experience from my position in the Software Engineering Lab at McGill and other notable projects. In addition I have experience with ArcGIS, mapping out regions in Spain and coastal Barbados for data collection projects. My aim is to combine my strong communication and presentation skills with my technical background in a Technical Consulting/Sales, Big Data/Network Engineer, Project Manager or Business Analyst role.",
          positions: 5,
          picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAg9AAAAJGFiOGM1ZDg0LTEyYTMtNGRhYS05ZDA0LTgyOWExMmNiNDYzNA.jpg',
          public_profile_url: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAg9AAAAJGFiOGM1ZDg0LTEyYTMtNGRhYS05ZDA0LTgyOWExMmNiNDYzNA.jpg",
          position_company_name: JSON.stringify(['Amazon Web Services']),
          position_company_industry: JSON.stringify(['Technology']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['San Francisco Bay Area']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['SDE Intern at Amazon Web Services'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC34mn',
          first_name: 'Ashley',
          last_name: 'Wei',
          email_address: 'ashleywei@gmail.com',
          headline: "Traffic Engineer, EIT at R.F. Binnie & Associates Ltd",
          location: 'Richmond, British Columbia, Canada',
          industry: 'Engineer',
          current_share: '',
          num_connections: 226,
          summary: "Traffic engineer, passionate about building a safer transportation environment",
          positions: 5,
          picture_url: 'https://s-media-cache-ak0.pinimg.com/originals/20/44/c8/2044c8c89a60a37a1ae247c17d935c4e.jpg',
          public_profile_url: "https://s-media-cache-ak0.pinimg.com/originals/20/44/c8/2044c8c89a60a37a1ae247c17d935c4e.jpg",
          position_company_name: JSON.stringify(['R.F.Binnie & Associates Ltd.']),
          position_company_industry: JSON.stringify(['Engineer']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Burnaby, British Columbia, Canada']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['Traffic Engineer, EIT'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC434mn',
          first_name: 'Meagan',
          last_name: 'Page',
          email_address: 'meaganpage@gmail.com',
          headline: "Software Sales Professional",
          location: 'Vancouver, British Columbia, Canada',
          industry: 'Software',
          current_share: '20',
          num_connections: 500,
          summary: "A dynamic and enthusiastic individualm natural leader. With superb communication skills and ability to think on my feet, being an ideal ambassador for your business and its ethics. Obtains managerial and leadership skills, and more than able to build up a business within established company standards, policies and procedures.",
          positions: 4,
          picture_url: 'https://s-media-cache-ak0.pinimg.com/originals/aa/e7/9c/aae79ce32a75827b35591a947f200d70.jpg',
          public_profile_url: "https://s-media-cache-ak0.pinimg.com/originals/aa/e7/9c/aae79ce32a75827b35591a947f200d70.jpg",
          position_company_name: JSON.stringify(['Trello']),
          position_company_industry: JSON.stringify(['Software Sales']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Vancouver, British Columbia, Canada']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['Inside Sales Representative'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FCASXA234mn',
          first_name: 'Alvis',
          last_name: 'Demo',
          email_address: 'alvisdemo@gmail.com',
          headline: "Data Scientist, Real-Time Analytics",
          location: 'Toronto, Ontario, Canada',
          industry: 'Banking, Technology',
          current_share: '',
          num_connections: 358,
          summary: "Currently redefining the retail banking experience through analytics driven decisioning• R • Orange • SAS factory miner • Python• SQL • Hive • Alteryx",
          positions: 5,
          picture_url: 'http://www.paulfrisbie.com/downloads/headshots/frisbie_cartoon.jpg',
          public_profile_url: "http://www.paulfrisbie.com/downloads/headshots/frisbie_cartoon.jpg",
          position_company_name: JSON.stringify(['Scotia Bank']),
          position_company_industry: JSON.stringify(['Finance, Technology']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Toronto, Ontario, Canada']),
          position_company_summary: JSON.stringify([""]),
          position_company_title: JSON.stringify(['Data Scientist'])
        }),
          knex('users').insert({
          linkedin_id: 'I2FC4CASC34mn',
          first_name: 'Jen',
          last_name: 'Wong',
          email_address: 'jenniferwong@gmail.com',
          headline: "Front Desk Receiptionist At McGill University",
          location: 'Montreal, British Columbia, Canada',
          industry: 'Education',
          current_share: '',
          num_connections: 107,
          summary: "Experienced Front Desk Receptionist with a demonstrated history of working in the higher education industry. Skilled in Customer Service, Event Planning and Management, Teaching, Translation and Research. Strong administrative professional with a Graduate Diploma focused on Applied Marketing and a Bachelor of Arts in East Asian Studies and Sociology from McGill University",
          positions: 7,
          picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAOsAAAAJDY3OGRkZWQ1LWNlNWEtNDg3Mi04ZGE3LWJlMTdiYTM1YmQ1Mw.jpg',
          public_profile_url: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAOsAAAAJDY3OGRkZWQ1LWNlNWEtNDg3Mi04ZGE3LWJlMTdiYTM1YmQ1Mw.jpg",
          position_company_name: JSON.stringify(['McGill']),
          position_company_industry: JSON.stringify(['Education']),
          position_company_type: JSON.stringify(['']),
          position_company_location: JSON.stringify(['Montreal, British Columbia, Canada']),
          position_company_summary: JSON.stringify(["Responded to general inquiries and answered questions from students, staff and the public about the SSMU, McGill campus and its services Responded to e-mails with similar inquiries"]),
          position_company_title: JSON.stringify(['Front Desk Receiptionist'])
        }),
        knex('users').insert({
          linkedin_id: 'I234Ay343a',
          first_name: 'Steve',
          last_name: 'Wozniak',
          email_address: 's.wozniak@sandisk.com',
          headline: 'Fellow at Apple',
          location: 'San Francisco, Bay Area',
          industry: 'Computer Software',
          current_share: '',
          num_connections: 500,
          summary: '',
          positions: 1,
          picture_url: 'http://pmc.com/wp-content/uploads/2014/07/03_PMC_Board_Bio_Wozniak-289x407.png',
          public_profile_url: 'http://pmc.com/wp-content/uploads/2014/07/03_PMC_Board_Bio_Wozniak-289x407.png',
          position_company_name: JSON.stringify(['Fusion-io']),
          position_company_industry: JSON.stringify(['Software']),
          position_company_type: JSON.stringify(['Technology']),
          position_company_location: JSON.stringify(['']),
          position_company_summary: JSON.stringify(['I\'m looking into future technologies applicable to servers and storage, and helping this company, which I love, get noticed and get a lead so that the world can discover the new amazing technology they have developed. My role is principally a marketing one at present but that will change over time.']),
          position_company_title: JSON.stringify(['Chief Scientist'])
        })
      ]);
    });
};
